title: Welcome to My website
description: A site about stuff
url: https://abhijrathod.github.io/
author: Abhijeet Rahod
avatar: https://www.gravatar.com/avatar/1234567890abcdef1234567890abcdef
paginate: 5
comments: true
google_analytics: UA-12345678-9
# Minima theme
theme: minima

